name: "Is my docker parent image out-of-date?"

description: "Checks if your image uses an out-of-date parent image. Use this do determine whether you need to rebuild your image."

author: twiddler

inputs:
  parent-image:
    description: "The docker parent image you are building on top"
    required: true

  my-image:
    description: "Your image"
    required: true

outputs:
  out-of-date:
    description: "'true' if your image does NOT use an up-to-date parent image, 'false' otherwise."

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.my-image }}
    - ${{ inputs.parent-image }})

branding:
  icon: refresh-ccw
  color: green
