on:
  push:

jobs:
  dind:
    runs-on: ubuntu-latest

    env:
      DOCKER_CONFIG: $HOME/.docker

    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker://docker
        with:
          entrypoint: docker
          args: info
