name: Test

on: [push, workflow_dispatch]

jobs:
  test-known-images:
    name: Let's see if this works as intended

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]
        parent-image: ["nginx:1.21.0", ubuntu]
        my-image: ["nginx/nginx-ingress:1.12.0", ubuntu]

    steps:
      - uses: actions/checkout@v2

      - id: check
        uses: ./
        with:
          parent-image: ${{ matrix.parent-image }}
          my-image: ${{ matrix.my-image }}

      - run: ./tests/assert-out-of-date.sh "${{ matrix.my-image }}" "${{matrix.parent-image }}"
        shell: bash
        if: steps.check.outputs.out-of-date == 'true'

      - run: ./tests/assert-up-to-date.sh "${{ matrix.my-image }}" "${{matrix.parent-image }}"
        shell: bash
        if: steps.check.outputs.out-of-date == 'false'

  fail-on-unknown-parent-image:
    name: We should fail if we cannot find `parent-image`

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]
        parent-image: [qwertzui]
        my-image: [alpine, asdfghjk]

    steps:
      - uses: actions/checkout@v2

      - id: check
        uses: ./
        with:
          parent-image: ${{ matrix.parent-image }}
          my-image: ${{ matrix.my-image }}
        continue-on-error: true

      - run: exit 1
        shell: bash
        if: steps.check.outputs.out-of-date != ''

  fail-on-unknown-my-image:
    name: We should fail if we cannot find `my-image`

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]
        parent-image: [alpine, asdfghjk]
        my-image: [qwertzui]

    steps:
      - uses: actions/checkout@v2

      - id: check
        uses: ./
        with:
          parent-image: ${{ matrix.parent-image }}
          my-image: ${{ matrix.my-image }}
        continue-on-error: true

      - run: exit 1
        shell: bash
        if: steps.check.outputs.out-of-date != ''
