name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    name: Let's see if this works

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        parent-image: [nginx:1.21.0]
        my-image: [nginx/nginx-ingress:1.12.0]

    steps:
      - uses: actions/checkout@v2

      - id: check
        uses: ./
        with:
          parent-image: ${{ matrix.parent-image }}
          my-image: ${{ matrix.my-image }}
