name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    name: Let's see if this works

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04, ubuntu-18.04]

    steps:
      - uses: actions/checkout@v2

      - id: check
        uses: ./
        with:
          parent-image: nginx:1.21.0
          my-image: nginx/nginx-ingress:1.12.0

      - run: |
          echo "My image uses the up-to-date parent image. So this should NOT run."
          exit 1
        if: steps.check.outputs.out-of-date == 'true'

      - run: |
          echo "My image uses the up-to-date parent image. So this should run."
        if: steps.check.outputs.out-of-date == 'false'
